<?php
// $Id$
/**
 * @file
 * Provides connection to Instapaper service
 */

/**
 * Implementation of hook_help().
 */
function instapaper_help($path, $arg) {
  switch ($path) {
    case 'admin/help#instapaper':
      return t('Provides functionality to interface with the Instapaper web service to allow offline reading.');
  }
}


/**
 * Implementation of hook_menu().
 */
function instapaper_menu() {
  $items['admin/settings/service_links/instapaper'] = array(
    'title' => t('Instapaper'),
    'description' => t('Configuration options for the Instapaper service.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('instapaper_admin_settings'),
    'access arguments' => array('administer service links'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'instapaper.admin.inc',
  );
  return $items;
}


/**
 * Implementation of hook_service_links().
 *
 * See the Service Links module.
 */
function instapaper_service_links() {
  $links['instapaper'] = array(
    'name' => 'Read Later',
    'description' => t('Read Later with Instapaper'),
    // 'link' => 'http://www.instapaper.com/e2?url=<encoded-url>&title=<encoded-title>',
    'link' => 'http://www.instapaper.com/hello2?u=<encoded-url>&t=<encoded-title>',
    'icon' => drupal_get_path('module', 'instapaper') .'/images/' . variable_get('instapaper_icon', 'instapaper.png'),
//    'javascript' => 'http://www.instapaper.com/javascript/embed2.js?ver=1.1',
//    'callback' => 'instapaper_embed',
  );
  return $links;
}
